name: Update and Deploy Shiny App

on:
  schedule:
    - cron: '0 7 * * *'  # runs daily at 7 AM UTC (midnight PDT)
  workflow_dispatch:      # allows manual trigger in GitHub Actions UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Check out repo
        uses: actions/checkout@v3

      - name: 📦 Set up R
        uses: r-lib/actions/setup-r@v2

      - name: 🧰 Install required R packages
        run: |
          Rscript -e 'install.packages(c("rsconnect", "arrow", "tidyverse", "bslib", "DT",
          "shinyWidgets","conflicted","plotly","dataRetrieval","bsicons","viridis","scales",
          "fontawesome","leaflet","leafem"))'

      - name: 🛠️ Run data update script
        run: Rscript ptagis_processing.R

      - name: 🚀 Deploy to shinyapps.io
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript -e 'rsconnect::setAccountInfo(name = "yourname", token = Sys.getenv("SHINYAPPS_TOKEN"), secret = Sys.getenv("SHINYAPPS_SECRET"))'
          Rscript -e 'rsconnect::deployApp(appDir = ".", forceUpdate = TRUE)'
