name: Update and Deploy Shiny App

on:
  schedule:
    - cron: '0 9 * * *'  # runs daily at 9 AM UTC (2 AM PDT)
  workflow_dispatch:      # allows manual trigger in GitHub Actions UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Check out repo
        uses: actions/checkout@v3
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: 📦 Set up R
        uses: r-lib/actions/setup-r@v2

      - name: 🧰 Install required R packages
        run: |
          Rscript -e 'options(repos = c(CRAN = "https://cloud.r-project.org")); 
          install.packages(c("vroom","conflicted","curl","httr2","dataRetrieval","dplyr","stringr","lubridate",
          "rsconnect"))'

      - name: 🛠️ Run data update script
        run: Rscript ptagis_processing.R
        
      - name: 🐛 Check for data/ contents
        run: |
         echo "=== Does data/ exist? ==="
         if [ -d "data" ]; then echo "Yes, data/ exists."; else echo "No, data/ does NOT exist."; fi
         echo ""
         echo "=== Listing contents of data/ ==="
         ls -la data || echo "data/ folder is missing or empty"



      - name: 🚀 Deploy to shinyapps.io
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript -e 'rsconnect::setAccountInfo(name = "elifelts", token = Sys.getenv("SHINYAPPS_TOKEN"), secret = Sys.getenv("SHINYAPPS_SECRET"))'
          Rscript -e 'rsconnect::deployApp(appDir = ".", forceUpdate = TRUE, appFiles = list.files(".", recursive=TRUE))'
